# Generated by Django 3.2.9 on 2021-12-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.CharField(choices=[('BS', 'Basic Service'), ('OC', 'Oil Change'), ('RAF', 'Replace air filter'), ('BR', 'Battery replacement'), ('WB', 'Wheels align/balance'), ('AF', 'Antifreeze added')], default=0, max_length=3)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
