# Generated by Django 3.2.9 on 2021-12-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211211_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('BS', 'Basic Service'), ('OC', 'Oil Change'), ('RAF', 'Replace air filter'), ('BR', 'Battery replacement'), ('WB', 'Wheels align/balance'), ('AF', 'Antifreeze added')], default='BS', max_length=3),
        ),
    ]
