# Generated by Django 3.2.9 on 2022-01-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='category',
        ),
    ]
