# Generated by Django 3.2.9 on 2022-01-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_service_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category',
            new_name='service',
        ),
    ]
